services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    env_file: ./docker_config/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - conf.d:/etc/nginx/conf.d
      - ./docker_config/nginx.tmpl:/app/nginx.tmpl:rw
    networks:
      - bridge-network
  
networks:
  bridge-network:
    driver: bridge

volumes:
  conf.d:
  vhostd:
  html:
  acme:
  dbdata:
