---
instance:
  name: ${PROJECT_NAME:Docker Container}
  # ip: "192.168.0.1" # In case you need hardcoded IP address.
custom_alerts:
  space_critical: 10
  space_warning: 30
backup:
  target_directory: "/Backups"
database:
  hostname: ${WORDPRESS_DB_HOST} # Non-mandatory, localhost default value.
  user: root
  password: ${MYSQL_ROOT_PASSWORD}
projects:
  - cmaxima_web_wp:
    site:
      path: "/var/www/html"
      backup_frequency: 24 # Hours
      compress: True
      preserve: False
    schema:
      name: ${WORDPRESS_DB_NAME}
      backup_frequency: 720 # Hours
      compress: True
      preserve: False
aws:
  region: ${AWSCLI_REGION}
  access_key_id: ${AWSCLI_ACCESS_KEY_ID}
  secret_access_key: ${AWSCLI_SECRET_ACCESS_KEY}
bucket:
  name: ${S3_BACKUP_BUCKET}
sendgrid: True # Only true if the variable is stored in AWS' Secret Manager
innova_monitor: True # Only true if the variable is stored in AWS' Secret Manager
responsibles:
  - nrmn:
    name: "nrmn"
    email: "n0rmvnnn@gmail.com"
...
