services:

  mongodb:
    image: mongo
    container_name: mongodb 
    restart: always
    expose:
     - 27017
    env_file: .env
    networks:
     - internal-network

  hexacore-api:
    image: ${IMAGE_DOCKER} 
    container_name: ${PROYECT_NAME}-api  
    restart: always
    expose: 
     - 80  
    env_file: .env
    stdin_open: true    
    tty: true
    depends_on:
     - mongodb
    links:
     - mongodb
    
    networks:
     - docker_bridge-network
     - internal-network
     
       # labels:
       #- "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"

volumes:

  schemas:
  certs:
  html:
  vhostd:
  dbdata:
  acme:

networks:

  docker_bridge-network:
    external: true
  
  internal-network:
    driver: bridge
